// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5q0c0heOCxkzOqHzOJjC2Noh_WnzcDM',
    appId: '1:883121735597:web:095960fc00912cb2d0c324',
    messagingSenderId: '883121735597',
    projectId: 'chat-d3095',
    authDomain: 'chat-d3095.firebaseapp.com',
    storageBucket: 'chat-d3095.appspot.com',
    measurementId: 'G-F4J99PX2PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgEzOpJksjwUXhdrWit6AEpDzrq2kKzhs',
    appId: '1:883121735597:android:a7bd29a9f4ea9ef2d0c324',
    messagingSenderId: '883121735597',
    projectId: 'chat-d3095',
    storageBucket: 'chat-d3095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2op3vc1aPjR4QewVmWBzunBWqbI7JXdU',
    appId: '1:883121735597:ios:e56dbe7ae73ef152d0c324',
    messagingSenderId: '883121735597',
    projectId: 'chat-d3095',
    storageBucket: 'chat-d3095.appspot.com',
    iosClientId: '883121735597-cj6nvnv0b6ule4ts89ce2frn94vo528a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
